function [summariesx,summariesy] = nonlingauss_summaries(xhat,yobssim)
% compute summary statistics for both X and Y across all simulations
% (vectorised code)

if ~isempty(xhat)
   summariesx = [
                median(xhat,1);...
                mad(xhat,1,1);...
                prctile(xhat,10);...
                prctile(xhat,25);...
                prctile(xhat,75);...
                prctile(xhat,90)];
  summariesy = [
                median(yobssim,1);...
                mad(yobssim,1,1);...
                prctile(yobssim,10);...
                prctile(yobssim,25);...
                prctile(yobssim,75);...
                prctile(yobssim,90)];
elseif isempty(xhat)
    summariesx = [];
    summariesy = [
                  median(yobssim,1);...
                  mad(yobssim,1,1);
                  prctile(yobssim,10);...
                  prctile(yobssim,25);...
                  prctile(yobssim,75);...
                  prctile(yobssim,90)];
end


end

